//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieDictionary.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoviesEntities : DbContext
    {
        public MoviesEntities()
            : base("name=MoviesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Badges> Badges { get; set; }
        public virtual DbSet<ForumPosts> ForumPosts { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<ReviewsLikes> ReviewsLikes { get; set; }
        public virtual DbSet<UsersBadges> UsersBadges { get; set; }
        public virtual DbSet<UsersFriendships> UsersFriendships { get; set; }
        public virtual DbSet<UsersRecommendations> UsersRecommendations { get; set; }
        public virtual DbSet<UsersWatchlists> UsersWatchlists { get; set; }
        public virtual DbSet<UsersRatings> UsersRatings { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<PostsLikes> PostsLikes { get; set; }
        public virtual DbSet<LatestMovies> LatestMovies { get; set; }
        public virtual DbSet<ApplicationConfigurations> ApplicationConfigurations { get; set; }
        public virtual DbSet<Movies> Movies { get; set; }
        public virtual DbSet<NotificationTypes> NotificationTypes { get; set; }
        public virtual DbSet<UsersNotifications> UsersNotifications { get; set; }
    }
}
