//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieDictionary.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersNotifications
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public bool Seen { get; set; }
        public int NotificationTypeId { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string MovieId { get; set; }
        public Nullable<int> BadgeId { get; set; }
        public Nullable<int> PostId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Badges Badges { get; set; }
        public virtual ForumPosts ForumPosts { get; set; }
        public virtual Movies Movies { get; set; }
        public virtual NotificationTypes NotificationTypes { get; set; }
    }
}
