//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieDictionary.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersRatings
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string MovieId { get; set; }
        public int Rating { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Movies Movies { get; set; }
    }
}
